name: dodge
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.7.0.149
  - libcurand=10.3.3.53
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.10.0
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.15.2
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.28.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - cachetools==5.3.3
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - diffusers==0.27.2
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.22.2
      - imageio==2.34.0
      - importlib-metadata==7.1.0
      - ipdb==0.13.13
      - ipython==8.23.0
      - jedi==0.19.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.3
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - nvidia-ml-py==12.535.133
      - nvitop==1.3.2
      - opencv-python==4.9.0.80
      - packaging==24.0
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - regex==2023.12.25
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tifffile==2024.2.12
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.39.3
      - wandb==0.17.4
      - wcwidth==0.2.13
      - xformers==0.0.25.post1
      - zipp==3.18.1
prefix: /home/jaehyun/anaconda3/envs/dodge
